<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="3" total="7" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="14772" started-at="2019-08-22T13:31:26Z" finished-at="2019-08-22T13:31:41Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="14772" started-at="2019-08-22T13:31:26Z" finished-at="2019-08-22T13:31:41Z">
      <class name="com.application.testcases.TC02_GetUserDetails">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="beforeSuite" is-config="true" duration-ms="787" started-at="2019-08-22T13:31:25Z" finished-at="2019-08-22T13:31:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="beforeClass" is-config="true" duration-ms="2" started-at="2019-08-22T13:31:26Z" finished-at="2019-08-22T13:31:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="beforeMethod" is-config="true" duration-ms="12" started-at="2019-08-22T13:31:27Z" finished-at="2019-08-22T13:31:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="validateUserDetails(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="validateUserDetails" duration-ms="7298" started-at="2019-08-22T13:31:27Z" data-provider="fetchData" finished-at="2019-08-22T13:31:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://gorest.co.in/public-api/users]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[post]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Bearer L41uyhzxoig9roHjTyRHFvBT48K2GjCMjbVC]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[{"email": "john@gmail.com","first_name": "john","last_name": "cena","gender": "male"}]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at com.framework.utils.Reporter.reportStep(Reporter.java:47)
at com.application.testcases.TC02_GetUserDetails.validateUserDetails(TC02_GetUserDetails.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserDetails -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="afterMethod" is-config="true" duration-ms="1" started-at="2019-08-22T13:31:34Z" finished-at="2019-08-22T13:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:34Z" finished-at="2019-08-22T13:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="validateUserDetails(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="validateUserDetails" duration-ms="2143" started-at="2019-08-22T13:31:34Z" data-provider="fetchData" finished-at="2019-08-22T13:31:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://gorest.co.in/public-api/users]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[get]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Bearer L41uyhzxoig9roHjTyRHFvBT48K2GjCMjbVC]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at com.framework.utils.Reporter.reportStep(Reporter.java:47)
at com.application.testcases.TC02_GetUserDetails.validateUserDetails(TC02_GetUserDetails.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserDetails -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:36Z" finished-at="2019-08-22T13:31:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="afterTest" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:41Z" finished-at="2019-08-22T13:31:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="afterSuite" is-config="true" duration-ms="716" started-at="2019-08-22T13:31:41Z" finished-at="2019-08-22T13:31:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.application.testcases.TC02_GetUserDetails -->
      <class name="com.application.testcases.TC01_CreateUser">
        <test-method status="PASS" signature="setData()[pri:0, instance:com.application.testcases.TC02_GetUserDetails@598067a5]" name="setData" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:26Z" finished-at="2019-08-22T13:31:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="setData()[pri:0, instance:com.application.testcases.TC01_CreateUser@3c0ecd4b]" name="setData" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:26Z" finished-at="2019-08-22T13:31:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.application.testcases.TC01_CreateUser@3c0ecd4b]" name="beforeClass" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:36Z" finished-at="2019-08-22T13:31:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.application.testcases.TC01_CreateUser@3c0ecd4b]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-08-22T13:31:37Z" finished-at="2019-08-22T13:31:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="createUser(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.application.testcases.TC01_CreateUser@3c0ecd4b]" name="createUser" duration-ms="2024" started-at="2019-08-22T13:31:37Z" data-provider="fetchData" finished-at="2019-08-22T13:31:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://gorest.co.in/public-api/users]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[post]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Bearer L41uyhzxoig9roHjTyRHFvBT48K2GjCMjbVC]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[{"email": "john@gmail.com","first_name": "john","last_name": "cena","gender": "male"}]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at com.framework.utils.Reporter.reportStep(Reporter.java:47)
at com.application.testcases.TC01_CreateUser.createUser(TC01_CreateUser.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.application.testcases.TC01_CreateUser@3c0ecd4b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:39Z" finished-at="2019-08-22T13:31:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="createUser(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.application.testcases.TC01_CreateUser@3c0ecd4b]" name="createUser" duration-ms="2088" started-at="2019-08-22T13:31:39Z" data-provider="fetchData" finished-at="2019-08-22T13:31:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://gorest.co.in/public-api/users]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[get]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Bearer L41uyhzxoig9roHjTyRHFvBT48K2GjCMjbVC]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at com.framework.utils.Reporter.reportStep(Reporter.java:47)
at com.application.testcases.TC01_CreateUser.createUser(TC01_CreateUser.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.application.testcases.TC01_CreateUser@3c0ecd4b]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:39Z" finished-at="2019-08-22T13:31:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.application.testcases.TC01_CreateUser@3c0ecd4b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-08-22T13:31:41Z" finished-at="2019-08-22T13:31:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.application.testcases.TC01_CreateUser -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
